name: github pages

on:
  push:
    branches:
      - main-pl
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '12.x'
          check-latest: true

      - name: Prepare site
        run: |
             npm install
             cp -r ./.github/data/ ./node_modules/@openacr/openacr/catalog/
             cp -rv ./.github/src/ ./node_modules/@openacr/openacr/
             cp -rv ./.github/tests/ ./node_modules/@openacr/openacr/
             cd ./node_modules/@openacr/openacr/
             npx ts-node ./src/librarian.ts -c WCAG
             npx ts-node ./src/librarian.ts -c WCAG-21
             npx ts-node ./src/librarian.ts -c WCAG21-508
             npx ts-node ./src/librarian.ts -c WCAG22-508
             npx ts-node ./src/librarian.ts -c 508
             npx ts-node ./src/librarian.ts -c EU
             npx ts-node ./src/librarian.ts -c INT
             npx ts-node ./src/librarian.ts -c WCAG22-EU
             cd ${{ github.workspace }}
             export NODE_ENV=ghpages && npm run build
             cd public && ln -s index.html 404.html # symlink for GH pages fallback
      
      - name: Upload production-ready assets
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

